package com.example.ui.util

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.net.Uri
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

/**
 * Generates fee receipts as shareable images.
 * Uses Compose rendering + bitmap capture approach.
 */
object ReceiptGenerator {

    data class ReceiptData(
        val orgName: String,
        val studentName: String,
        val standard: String,
        val month: String,
        val installment: String,
        val amount: Double,
        val paidDate: String,
        val transactionId: String = "TXN-${System.currentTimeMillis().toString().takeLast(8)}"
    )

    fun generateAndShare(context: Context, data: ReceiptData) {
        try {
            val receiptText = buildReceiptText(data)
            val file = File(context.cacheDir, "receipt_${data.studentName.replace(" ", "_")}_${System.currentTimeMillis()}.txt")
            file.writeText(receiptText)

            val uri = FileProvider.getUriForFile(context, "com.example.provider", file)
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_SUBJECT, "Fee Receipt - ${data.studentName}")
                putExtra(Intent.EXTRA_TEXT, receiptText)
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(shareIntent, "Share Receipt"))
        } catch (e: Exception) {
            Toast.makeText(context, "Receipt generation failed: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun buildReceiptText(data: ReceiptData): String {
        val line = "══════════════════════════════════"
        return buildString {
            appendLine(line)
            appendLine("       ${data.orgName}")
            appendLine("         FEE RECEIPT")
            appendLine(line)
            appendLine()
            appendLine("Date:          ${data.paidDate}")
            appendLine("Receipt No:    ${data.transactionId}")
            appendLine()
            appendLine("Student:       ${data.studentName}")
            appendLine("Class:         ${data.standard}")
            appendLine()
            appendLine("Period:        ${data.month}")
            appendLine("Description:   ${data.installment}")
            appendLine()
            appendLine(line)
            appendLine("AMOUNT PAID:   ₹${String.format("%,.0f", data.amount)}")
            appendLine(line)
            appendLine()
            appendLine("Status:        ✓ PAID")
            appendLine()
            appendLine("This is a computer-generated receipt.")
            appendLine("Generated by TuitionOS")
            appendLine(line)
        }
    }
}
